### ISSUE TITLE
Use bespoke face instead of implicit dependency on anzu

### ISSUE THREAD

**Issue by protesilaos** [ksafford/bannedit#2]
Thank you for sharing this!

I just noticed that `bannedit-face` is assigned to a face that is provided by the `anzu` package.  This will not work as intended if the user does not have that package installed.

You could instead specify one of the faces in `M-x find-library RET faces RET`, or define one yourself.

Here is a sample diff for defining a face that inherits from `highlight`.  This has the benefit that themes can configure it easily.

```diff
 bannedit.el | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/bannedit.el b/bannedit.el
index 96d038f..399dc67 100644
--- a/bannedit.el
+++ b/bannedit.el
@@ -66,11 +66,15 @@
 
 (sequencep bannedit-words)
 
-(defcustom bannedit-face 'anzu-match-1
+(defcustom bannedit-face 'bannedit-highlight
   "Face to use when highlighting banned words."
   :type 'face
   :group 'bannedit)
 
+(defface bannedit-highlight '((t :inherit highlight))
+  "Face for highlighting phrases in `bannedit-mode'."
+  :group 'bannedit)
+
 (defvar bannedit-switch t)
 
 (defun bannedit-phrase-to-case-insensitive-regex (phrase)
```

**Comment by ksafford** [comment]
Thanks for this. Extremely informative comment here. I'm not particularly familiar with faces so I really appreciate your advice. 

I've just now read the documentation for defface and a few posts about defining faces. If I understand properly, in the spec given to `defface` here, the property `:inherit highlight` will use whatever the current theme sets for the highlight face. Which is definitely the right thing to do. 

Also, I'd like to say I really enjoy your videos and am a huge fan of the modus themes. I'll add a credit to the theme along side the gif I've uploaded.

**Comment by protesilaos** [comment]
> If I understand properly [...] will use whatever the current theme sets for the highlight face.

Correct!

Depending on how your project evolves, you may want to check how other similar tools are styling their highlights.  Maybe you wish to have things underlined, a different text+background combination, etc.  If you need help, feel free to contact me.

> Also, I'd like to say I really enjoy your videos and am a huge fan of the modus themes.

Thanks!
